### ISSUE TITLE
Command reference docs

### ISSUE THREAD

**Issue by mcbain** [beetlebugorg/mod_dims#12]
Is there any reference document with all supported commands incl. params ?

**Comment by lkwg82ATis24** [comment]
I did searched too and failed, please add some information.

**Comment by lkwg82ATis24** [comment]
A kind of list of operations: https://github.com/beetlebugorg/mod_dims/blob/master/src/mod_dims.c#L1512

**Comment by lkwg82ATis24** [comment]
Try also to check our fork: https://github.com/ImmobilienScout24/mod-dims

**Comment by lkwg82ATis24** [comment]
Do you really think the code is valid documentation?

**Comment by mcbain** [comment]
Hallo Lars, bin Jens Zastrow von IS24 :)
Glaube ich wollte im letztes November mal wissen was es so alles für Funktionen beim SOD gibt, da der ja mod_dims verwendet.

**Comment by lkwg82ATis24** [comment]
Lol, genau die gleiche Frage, habe ich mir gestern auch gestellt und mal recherchiert.

Will demnächst mit Sven S. eine Erweiterung einbringen. 

Dazu sollten wir mal Kaffee trinken ;)
