### ISSUE TITLE
Issue with ImageMagick 6.9.11-60_0

### ISSUE THREAD

**Issue by sshyub** [beetlebugorg/mod_dims#36]
FTR,
*mod_dims* caused Apache to crash without any logs even with debug log level set if complied with  *ImageMagick 6.9.11-60_0* on macOS 10.14.6.

Here are the versions of other dependencies.
curl @7.75.0_0
apache2 @2.4.46_1

**Comment by beetlebugorg** [comment]
I suspect this was caused by #37
